### ISSUE TITLE
sekireiでのmake.sys

### ISSUE THREAD

**Issue by takeohoshi** [issp-center-dev/Komega#2]
sekireiでbuildする際に使っているmake.sysを教えて欲しいです。
preinstallされているとはいえ、自分でも全く同じbuild作業をしておきたいです。

**Comment by mitsuaki1987** [comment]
河村です。
MateriAppsInstaller(主開発者:藤堂先生)
https://github.com/wistaria/MateriAppsInstaller/blob/master/11_Komega/sekirei.sh
によってインストールされていて、具体的なmake.sysは次のようになっています。
```
F90 = ifort
MPIF90 = mpif90
FFLAGS = -mkl=parallel -fpp -O3 -xCORE-AVX2
```

**Comment by takeohoshi** [comment]
コードがバージョンアップして状況が変わったので、このissueはcloseします。
