### ISSUE TITLE
COCG法のバグについて

### ISSUE THREAD

**Issue by yoshizawa56** [issp-center-dev/Komega#5]
komegaのv2.0.0でバグと思われるところを発見したので，ご報告いたします．

COCG法の計算を複数回行ったところ，2回目のkomega_COCG_initの呼び出し時に

At line 167 of file komega_cocg.F90
Fortran runtime error: Attempting to allocate already allocated variable 'lz_conv'

というエラーが出て，プログラムが終了しました．
komega_cocg.F90を確認してみたところ，komega_COCG_finalizeが

SUBROUTINE komega_COCG_finalize() BIND(C)
!
  USE komega_parameter, ONLY : itermax, lz_conv
  USE komega_vals_c, ONLY : alpha_save, beta_save, &
  &                                 pi, pi_old, pi_save, z
  USE komega_vecs_c, ONLY : p, r_l_save, v3
  !
  IMPLICIT NONE
  !
  DEALLOCATE(z, v3, pi, pi_old, p)
  !
  IF(itermax > 0) THEN
     DEALLOCATE(alpha_save, beta_save, r_l_save, pi_save, lz_conv)
  END IF
  !
END SUBROUTINE komega_COCG_finalize

となっており，itermax=0の場合に，lz_convの開放が行われていないことが原因のようでした．
if文の外に DEALLOCATE(lz_conv) を書き足したら，正しく動作するようになりました．

**Comment by mitsuaki1987** [comment]
ご報告どうもありがとうございます。
たしかにlz_convは常にdeallocateされるべき変数でした。ご不便おかけしてすみません。
修正したものを後ほどリリースします。
